"""add chunks table for phase 2 embeddings

Revision ID: a1d2208bc2ab
Revises: c9e5b34df732
Create Date: 2026-07-15 17:33:39.487292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a1d2208bc2ab'
down_revision: Union[str, Sequence[str], None] = 'c9e5b34df732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indexing_run_id'], ['indexing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indexing_run_id', 'node_id', name='uq_chunks_run_node')
    )
    op.create_index('idx_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunks_indexing_run_id'), 'chunks', ['indexing_run_id'], unique=False)
    op.create_index(op.f('ix_chunks_node_id'), 'chunks', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_node_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_indexing_run_id'), table_name='chunks')
    op.drop_index('idx_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks')
    # ### end Alembic commands ###
