"""initial schema

Revision ID: c9e5b34df732
Revises: 
Create Date: 2026-07-14 11:31:17.368461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e5b34df732'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('repo_path', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('edge_count', sa.Integer(), nullable=True),
    sa.Column('unresolved_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_path', 'commit_sha', name='uq_indexing_runs_repo_commit')
    )
    op.create_table('file_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('loc', sa.Integer(), nullable=False),
    sa.Column('function_count', sa.Integer(), nullable=False),
    sa.Column('git_churn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indexing_run_id'], ['indexing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indexing_run_id', 'file_path', name='uq_file_metrics_run_path')
    )
    op.create_index(op.f('ix_file_metrics_indexing_run_id'), 'file_metrics', ['indexing_run_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('node_type', sa.Enum('FILE', 'FUNCTION', 'METHOD', 'CLASS', name='node_type'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qualified_name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indexing_run_id'], ['indexing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indexing_run_id', 'qualified_name', 'node_type', name='uq_nodes_run_qualname_type')
    )
    op.create_index('idx_nodes_file_path', 'nodes', ['indexing_run_id', 'file_path'], unique=False)
    op.create_index('idx_nodes_name', 'nodes', ['indexing_run_id', 'name'], unique=False)
    op.create_index(op.f('ix_nodes_indexing_run_id'), 'nodes', ['indexing_run_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('edge_type', sa.Enum('CALLS', 'IMPORTS', 'CONTAINS', name='edge_type'), nullable=False),
    sa.Column('src_node_id', sa.BigInteger(), nullable=False),
    sa.Column('dst_node_id', sa.BigInteger(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dst_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indexing_run_id'], ['indexing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indexing_run_id', 'edge_type', 'src_node_id', 'dst_node_id', 'line', name='uq_edges_run_type_src_dst_line')
    )
    op.create_index('idx_edges_dst', 'edges', ['indexing_run_id', 'edge_type', 'dst_node_id'], unique=False)
    op.create_index('idx_edges_src', 'edges', ['indexing_run_id', 'edge_type', 'src_node_id'], unique=False)
    op.create_index(op.f('ix_edges_dst_node_id'), 'edges', ['dst_node_id'], unique=False)
    op.create_index(op.f('ix_edges_indexing_run_id'), 'edges', ['indexing_run_id'], unique=False)
    op.create_index(op.f('ix_edges_src_node_id'), 'edges', ['src_node_id'], unique=False)
    op.create_table('unresolved_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indexing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('src_node_id', sa.BigInteger(), nullable=False),
    sa.Column('called_name', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indexing_run_id'], ['indexing_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unresolved_calls_indexing_run_id'), 'unresolved_calls', ['indexing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unresolved_calls_indexing_run_id'), table_name='unresolved_calls')
    op.drop_table('unresolved_calls')
    op.drop_index(op.f('ix_edges_src_node_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_indexing_run_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_dst_node_id'), table_name='edges')
    op.drop_index('idx_edges_src', table_name='edges')
    op.drop_index('idx_edges_dst', table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_indexing_run_id'), table_name='nodes')
    op.drop_index('idx_nodes_name', table_name='nodes')
    op.drop_index('idx_nodes_file_path', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_file_metrics_indexing_run_id'), table_name='file_metrics')
    op.drop_table('file_metrics')
    op.drop_table('indexing_runs')
    # ### end Alembic commands ###
    # Autogenerate doesn't emit DROP TYPE for Postgres native enums; without this,
    # a downgrade-then-upgrade cycle fails with "type already exists".
    sa.Enum(name='node_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='edge_type').drop(op.get_bind(), checkfirst=True)
